name: 'load-env'
description: 'Load environment variables from a dotenv file'
author: 'duskmoon314'
inputs:
  files: # change this
    required: true
    description: 'dotenv files'
    default: '.env'
runs:
  using: 'node16'
  main: 'dist/index.js'
